### ISSUE TITLE
Monte-Carlo 2-step EI graphic

### ISSUE THREAD

**Issue by ah858** [ah858/bayesian-optimisation-blog#12]
- [ ] Sample the 2-step EI section using monte-carlo from left to right on the plot

**Implementation steps**
- [ ] 1. Randomly sample Gaussian point (for mean and var) --> Return y coord
- [ ] 2. Calculate EI for y coord
- [ ] 3. Plot EI as histogram bar
- [ ] 4. Repeat steps 1-3 10 times
- [ ] 5. Repeat for 30? samples across
- [ ] 6. Replace these points with a curve

Nice to haves:
- [ ] Fading points
